### ISSUE TITLE
Did the set up process change for mac with the newest version of R (4.0.2)?

### ISSUE THREAD

**Issue by nickcardamone** [lawalter/r-shiny-electron-app#2]
Hi.

Thanks for putting this together. I've been trying to set up my shiny app for mac using your method for a few hours now and I've gotten stuck. 

When I try and run the get-r-mac.sh it downloads 88 MB worth of files but I'm left with .pkgs not what should be there.
<img width="718" alt="Screen Shot 2020-12-07 at 3 28 10 PM" src="https://user-images.githubusercontent.com/70527146/101401796-d38ba800-38a0-11eb-854d-7bc29347f8d4.png">

I'm assuming that's limiting function of the Rscript add-cran-binary-pkgs.R because I get a bunch of warnings that the packages weren't found whenever I run that in the R terminal.

<img width="607" alt="Screen Shot 2020-12-07 at 3 29 25 PM" src="https://user-images.githubusercontent.com/70527146/101401904-003fbf80-38a1-11eb-800e-828910cc348a.png">

Also... I have laundry list of required packages for my app to run, do you think that's a problem? How do I ensure that all packages are available for my shiny app to eventually use in the electron framework?

<img width="347" alt="Screen Shot 2020-12-07 at 3 27 51 PM" src="https://user-images.githubusercontent.com/70527146/101401768-c969a980-38a0-11eb-9689-f8c66a1ff5d1.png">

Thanks again!

**Comment by lawalter** [comment]
Hi there! Thank you. Apologies for the delayed reply. Are you attempting to install 4.0.2 in the get-r-mac.sh step? Are you running version 4.0.2 of R currently? Do you have automagic installed? Since I haven't checked this process with the newest R, it's tough to say for sure what the cause of this issue is. I no longer have a mac available to run through these steps and check for you, unfortunately.

If you have your app in a folder called "shiny" and you have automagic installed, the following code in add-cran-binary-pkgs.R should check for all of the packages you need for your app to run. The rest of the script installs the packages .

`cran_pkgs <- setdiff(unique(c(
  "shiny",
  automagic::get_dependent_packages("shiny")
)), "automatic")`

Btw, you don't need to list both tidyverse and stringr/purrr, tidyverse imports both of them under its umbrella!
